Arithmetic
thisisrocee/Codelex_roCe pull request #2
Opened 2023-02-20 21:40 UTC by thisisrocee

2023-02-22 20:37 UTC, ausmoons requested changes

2023-02-22 20:37 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/CalculateArea/Program.cs
> +            while (true)
uz 4 būtu jāiziet

2023-02-22 20:37 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise11/Program.cs
> +    for (var i = 2; i <= Math.Sqrt(num); i++)
Te ir grūti saprast kas notiek ar return, jo nav salikti {}

2023-02-22 20:37 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise4/Program.cs
> +    for (var number = lower; number <= upper; number++) sum *= number;
Saliec {}

2023-02-22 20:37 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise6/Program.cs
> +        switch ((isCoza ? 1 : 0) | (isLoza ? 2 : 0) | (isWoza ? 4 : 0))
Ko šādu es redzu pirmo reizi šajā uzd :D

2023-02-23 06:04 UTC, thisisrocee commented on csharp-basics/exercises/Arithmetic/Exercise6/Program.cs
> +        switch ((isCoza ? 1 : 0) | (isLoza ? 2 : 0) | (isWoza ? 4 : 0))
Tas nozīmē, ka man jāizlabo? or jāpieliek komentārs ar paskaidrojumu?

2023-02-24 16:11 UTC, EdgarsSalmins commented on csharp-basics/exercises/Arithmetic/Exercise6/Program.cs
> +        switch ((isCoza ? 1 : 0) | (isLoza ? 2 : 0) | (isWoza ? 4 : 0))
vienkārši fakta konsttācija.. all good. :)

2023-03-18 15:25 UTC, ausmoons approved these changes
Sakārto failus un tad vari mergot

2023-03-18 15:25 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise11/Program.cs
> +    }
Pēc } jauna tukša rinda

2023-03-18 15:25 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise4/Program.cs
> +    sum *= number;
Tab. Pārskati visus failus

2023-03-20 13:10 UTC, merged