Classes and objects
thisisrocee/Codelex_roCe pull request #6
Opened 2023-03-04 09:32 UTC by thisisrocee

2023-03-05 05:36 UTC, ausmoons requested changes

2023-03-05 05:36 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Account/Account.cs
> +        public static void Transfer(Account from, Account to, double howMuch)
Šai metodei būtu jābūt program.cs. Tev te ir 2 dažādi account

2023-03-05 05:36 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise1/Program.cs
> +        private double Price;
private _name

2023-03-05 05:36 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise1/Program.cs
> +    class TestResult
Katra klase savā failā

2023-03-05 05:36 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise14/Program.cs
> +namespace Exercise14;
Te netrūkst {} zem namespace?

2023-03-05 05:36 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise4/Movie.cs
> +}
Tab nav ok

2023-03-05 05:36 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise6/Program.cs
> +        public void setMother(string mother)
Metodes ar lielo burtu

2023-03-05 05:36 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/VideoStore/Video.cs
> +        public int allRatings { get; private set; }
Ar lielo burtu

2023-03-05 05:36 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/VideoStore/VideoStore.cs
> +            Video video = _videos.Find(v => v.Title == title);
nav jāliek Video video var likt var video

2023-03-05 16:24 UTC, thisisrocee commented on csharp-basics/exercises/ClassesAndObjects/Exercise14/Program.cs
> +namespace Exercise14;
Man itkā resharper saka, ka tas vairs nav vajadzīgs, var iztikt ar ; , bet ja tas ir nozīmīgi varu salikt arī {}

2023-03-08 16:59 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise14/Program.cs
> +namespace Exercise14;
Visu citur ir likts. Izskatās dīvaini, ka pēkšņi kkur neliek

2023-03-08 17:07 UTC, ausmoons approved these changes

2023-03-08 17:07 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Account/Account.cs
> +        public double Money;
Kāpēc noņēmi private?

2023-03-08 17:07 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise4/Movie.cs
> +        public string Title;
Kāpēc te maini?

2023-03-09 18:53 UTC, thisisrocee commented on csharp-basics/exercises/ClassesAndObjects/Account/Account.cs
> +        public double Money;
Liekas lasāmāks un mazāks kods! ;)

2023-03-09 18:54 UTC, thisisrocee commented on csharp-basics/exercises/ClassesAndObjects/Exercise4/Movie.cs
> +        public string Title;
Jo, ja pārmainu uz public patīk atstāt rutīnu, public ar lielo, private ar _

2023-03-09 18:54 UTC, merged

2023-03-10 18:43 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise4/Movie.cs
> +        public string Title;
bet tev tur vajag private

2023-03-10 18:44 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Account/Account.cs
> +        public double Money;
Private bija pareizi. Ja nav skaidrs, jautā Edgaram

2023-03-10 18:44 UTC, thisisrocee commented on csharp-basics/exercises/ClassesAndObjects/Account/Account.cs
> +        public double Money;
aa okay

2023-03-10 18:44 UTC, thisisrocee commented on csharp-basics/exercises/ClassesAndObjects/Exercise4/Movie.cs
> +        public string Title;
ohh okay, paskatīšos!